# -*- mode: ruby -*-
# vim: set ft=ruby :
MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :box_version => "1804.02",
        :ip_addr => '192.168.11.101',
    :disks => {
        :sata1 => {
            :dfile => 'sata1.vdi',
            :size => 10240,
            :port => 1
        },
        :sata2 => {
            :dfile => 'sata2.vdi',
            :size => 2048, # Megabytes
            :port => 2
        },
        :sata3 => {
            :dfile => 'sata3.vdi',
            :size => 1024, # Megabytes
            :port => 3
        },
        :sata4 => {
            :dfile => 'sata4.vdi',
            :size => 1024,
            :port => 4
        }
    }
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.box_version = boxconfig[:box_version]

          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]
	 
	  box.vm.synced_folder ".", "/vagrant", disabled: true
          
	  box.vm.synced_folder "/home/timurhisamov/GITDIR/otus/lesson3/shared", "/vagrant"
	  
	  box.vm.provider :virtualbox do |vb|
                  vb.customize ["modifyvm", :id, "--memory", "200"]
#          vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
          vb.name = boxname.to_s

          boxconfig[:disks].each do |dname, dconf|
              unless File.exist?(dconf[:dfile])
                vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
              end
              vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]

          end
          end
      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
	  cp ~vagrant/.ssh/auth* ~root/.ssh
	  yum install -y epel-release 
	  yum install -y ncdu
          yum install -y vim psmisc
      SHELL

      end
  end
end
