# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
  :box_name => "centos/7",
  #:public => {:ip => '10.10.10.1', :adapter => 1},
  :net => [
    {ip: '', adapter: 2, netmask: "", virtualbox__intnet: "router-net"},
    {ip: '', adapter: 3, netmask: "", virtualbox__intnet: "router-net"},
  ]
},
:centralRouter => {
  :box_name => "centos/7",
  :net => [
    {ip: '', adapter: 2, netmask: "", virtualbox__intnet: "router-net"},
    {ip: '192.168.255.5', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "router-net1"},
    {ip: '192.168.255.9', adapter: 4, netmask: "255.255.255.252", virtualbox__intnet: "router-net2"},
    {ip: '192.168.0.1', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "central-net"},
    {ip: '', adapter: 6, netmask: "", virtualbox__intnet: "router-net"},
    #{ip: '192.168.0.33', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "hw-net"},
    #{ip: '192.168.0.65', adapter: 7, netmask: "255.255.255.192", virtualbox__intnet: "wifi-net"},
  ]
},
:office1Router => {
  :box_name => "centos/7",
  :net => [
    {ip: '192.168.255.6', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net1"},
    {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "dev-net1"},
    {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "testserv-net1"},
    {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "managers-net1"},
    {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "hw-net1"},
    {ip: '', adapter: 7, netmask: "", virtualbox__intnet: "testLAN"},
    {ip: '', adapter: 8, netmask: "", virtualbox__intnet: "testLAN"},
  ]
},
:office2Router => {
  :box_name => "centos/7",
  :net => [
    {ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net2"},
    {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev-net2"},
    {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "testserv-net2"},
    {ip: '192.168.1.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "hw-net2"},
  ]
},
:centralServer => {
  :box_name => "centos/7",
  :net => [
    {ip: '192.168.0.0', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "central-net"},
  ]
},
:office1Server => {
  :box_name => "centos/7",
  :net => [
    {ip: '192.168.2.194', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "hw-net1"},
  ]
},
:office2Server => {
  :box_name => "centos/7",
  :net => [
    {ip: '192.168.1.194', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "hw-net2"},
  ]
},
:testClient1 => {
  :box_name => "centos/7",
  :net => [
    {ip: '', adapter: 2, netmask: "", virtualbox__intnet: "testLAN"},
  ]
},
:testClient2 => {
  :box_name => "centos/7",
  :net => [
    {ip: '', adapter: 2, netmask: "", virtualbox__intnet: "testLAN"},
  ]
},
:testServer1 => {
  :box_name => "centos/7",
  :net => [
    {ip: '', adapter: 2, netmask: "", virtualbox__intnet: "testLAN"},
  ]
},
:testServer2 => {
  :box_name => "centos/7",
  :net => [
    {ip: '', adapter: 2, netmask: "", virtualbox__intnet: "testLAN"},
  ]
},
}

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = ENV['http_proxy']
    config.proxy.https    = ENV['https_proxy']
    config.proxy.no_proxy = ENV['no_proxy']
  end
  MACHINES.each do |boxname, boxconfig|
  config.vbguest.auto_update = false
  config.vm.box_check_update = false
  config.vm.define boxname do |box|
    box.vm.box = boxconfig[:box_name]
    box.vm.host_name = boxname.to_s
    config.vm.provider "virtualbox" do |v|
      v.memory = 256      
    end
    boxconfig[:net].each do |ipconf|
      box.vm.network "private_network", ipconf
    end
    
    if boxconfig.key?(:public)
      box.vm.network "public_network", boxconfig[:public]
    end
    box.vm.provision "shell", inline: <<-SHELL
    mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
    SHELL
    
    case boxname.to_s
      when "inetRouter"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          modprobe --first-time bonding
          echo "net.ipv4.conf.all.forwarding=1" >> /etc/sysctl.conf
          iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
          echo "DEVICE=bond0\nBOOTPROTO=none\nNM_CONTROLLED=no\nONBOOT=yes\nTYPE=Bond\nBONDING_MASTER=yes\nIPV6INIT=no\nBROADCAST=192.168.255.3\nIPADDR=192.168.255.1\nNETMASK=255.255.255.252\nNETWORK=192.168.255.0\nUSERCTL=no\nBONDING_OPTS='mode=4 miimon=100 lacp_rate=1'" > /etc/sysconfig/network-scripts/ifcfg-bond0
          echo "DEVICE=eth1\nBOOTPROTO=none\nONBOOT=yes\nMASTER=bond0\nSLAVE=yes\nNM_CONTROLLED=no\nTYPE=Ethernet" > /etc/sysconfig/network-scripts/ifcfg-eth1
          echo "DEVICE=eth2\nBOOTPROTO=none\nONBOOT=yes\nMASTER=bond0\nSLAVE=yes\nNM_CONTROLLED=no\nTYPE=Ethernet" > /etc/sysconfig/network-scripts/ifcfg-eth2
          systemctl restart network
      SHELL
      when "centralRouter"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          modprobe --first-time bonding
          echo "net.ipv4.conf.all.forwarding=1" >> /etc/sysctl.conf
          echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
          #echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
          echo "DEVICE=bond0\nBOOTPROTO=none\nNM_CONTROLLED=no\nONBOOT=yes\nTYPE=Bond\nBONDING_MASTER=yes\nIPV6INIT=no\nBROADCAST=192.168.255.3\nIPADDR=192.168.255.2\nNETMASK=255.255.255.252\nNETWORK=192.168.255.0\nUSERCTL=no\nBONDING_OPTS='mode=4 miimon=100 lacp_rate=1'" > /etc/sysconfig/network-scripts/ifcfg-bond0
          echo "DEVICE=eth1\nBOOTPROTO=none\nONBOOT=yes\nMASTER=bond0\nSLAVE=yes\nNM_CONTROLLED=no\nTYPE=Ethernet" > /etc/sysconfig/network-scripts/ifcfg-eth1
          echo "DEVICE=eth2\nBOOTPROTO=static\nBROADCAST=192.168.255.7\nIPADDR=192.168.255.5\nNETMASK=255.255.255.252\nNETWORK=192.168.255.4\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth2
          echo "DEVICE=eth3\nBOOTPROTO=static\nBROADCAST=192.168.255.11\nIPADDR=192.168.255.9\nNETMASK=255.255.255.252\nNETWORK=192.168.255.8\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth3
          echo "DEVICE=eth4:1\nBOOTPROTO=static\nBROADCAST=192.168.0.15\nIPADDR=192.168.0.1\nNETMASK=255.255.255.240\nNETWORK=192.168.0.0\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth4:1
          echo "DEVICE=eth4:2\nBOOTPROTO=static\nBROADCAST=192.168.0.63\nIPADDR=192.168.0.33\nNETMASK=255.255.255.192\nNETWORK=192.168.0.32\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth4:2
          echo "DEVICE=eth4:3\nBOOTPROTO=static\nBROADCAST=192.168.0.127\nIPADDR=192.168.0.65\nNETMASK=255.255.255.192\nNETWORK=192.168.0.64\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth4:3
          echo "DEVICE=eth5\nBOOTPROTO=none\nONBOOT=yes\nMASTER=bond0\nSLAVE=yes\nNM_CONTROLLED=no\nTYPE=Ethernet" > /etc/sysconfig/network-scripts/ifcfg-eth5
          #Routing
          echo "192.168.2.192/26 via 192.168.255.6 dev eth2" > /etc/sysconfig/network-scripts/route-eth2
          echo "192.168.1.192/26 via 192.168.255.10 dev eth3" > /etc/sysconfig/network-scripts/route-eth3
          systemctl restart network
      SHELL
      when "office1Router"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          echo "net.ipv4.conf.all.forwarding=1" >> /etc/sysctl.conf
          modprobe 8021q
          echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
          echo "DEVICE=eth1\nBOOTPROTO=static\nBROADCAST=192.168.255.7\nIPADDR=192.168.255.6\nNETMASK=255.255.255.252\nNETWORK=192.168.255.4\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth1
          echo "DEVICE=eth2\nBOOTPROTO=static\nBROADCAST=192.168.2.63\nIPADDR=192.168.2.1\nNETMASK=255.255.255.192\nNETWORK=192.168.2.0\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth2
          echo "DEVICE=eth3\nBOOTPROTO=static\nBROADCAST=192.168.2.127\nIPADDR=192.168.2.65\nNETMASK=255.255.255.192\nNETWORK=192.168.2.64\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth3
          echo "DEVICE=eth4\nBOOTPROTO=static\nBROADCAST=192.168.2.191\nIPADDR=192.168.2.129\nNETMASK=255.255.255.192\nNETWORK=192.168.2.128\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth4
          echo "DEVICE=eth5\nBOOTPROTO=static\nBROADCAST=192.168.2.255\nIPADDR=192.168.2.193\nNETMASK=255.255.255.192\nNETWORK=192.168.2.192\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth5
          echo "DEVICE=eth6.10\nONBOOT=yes\nVLAN=yes\nBOOTPROTO=static\nTYPE=Ethernet\nNM_CONTROLLED=no\nIPADDR=10.10.10.10\nPREFIX=24" > /etc/sysconfig/network-scripts/ifcfg-eth6.10
          echo "DEVICE=eth7.20\nONBOOT=yes\nVLAN=yes\nBOOTPROTO=static\nTYPE=Ethernet\nNM_CONTROLLED=no\nIPADDR=10.10.10.10\nPREFIX=24" > /etc/sysconfig/network-scripts/ifcfg-eth7.20
          systemctl restart network
      SHELL
      when "office2Router"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          echo "net.ipv4.conf.all.forwarding=1" >> /etc/sysctl.conf
          echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
          echo "DEVICE=eth1\nBOOTPROTO=static\nBROADCAST=192.168.255.11\nIPADDR=192.168.255.10\nNETMASK=255.255.255.252\nNETWORK=192.168.255.8\nGATEWAY=192.168.255.9\nONBOOT=yes\nDEFROUTE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth1
          echo "DEVICE=eth2\nBOOTPROTO=static\nBROADCAST=192.168.1.63\nIPADDR=192.168.1.1\nNETMASK=255.255.255.128\nNETWORK=192.168.1.0\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth2
          echo "DEVICE=eth3\nBOOTPROTO=static\nBROADCAST=192.168.1.191\nIPADDR=192.168.1.129\nNETMASK=255.255.255.192\nNETWORK=192.168.1.128\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth3
          echo "DEVICE=eth4\nBOOTPROTO=static\nBROADCAST=192.168.1.255\nIPADDR=192.168.1.193\nNETMASK=255.255.255.192\nNETWORK=192.168.1.192\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth4
          systemctl restart network
      SHELL
      when "centralServer"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
          echo "DEVICE=eth1\nBOOTPROTO=static\nBROADCAST=192.168.0.63\nIPADDR=192.168.0.34\nNETMASK=255.255.255.192\nNETWORK=192.168.0.32\nGATEWAY=192.168.0.33\nONBOOT=yes\nDEFROUTE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth1
          systemctl restart network
      SHELL
      when "office1Server"    
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
          echo "DEVICE=eth1\nBOOTPROTO=static\nBROADCAST=192.168.2.255\nIPADDR=192.168.2.194\nNETMASK=255.255.255.192\nNETWORK=192.168.2.192\nGATEWAY=192.168.2.193\nONBOOT=yes\nDEFROUTE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth1
          systemctl restart network
      SHELL
      when "office2Server"    
      box.vm.provision "shell", run: "always", inline: <<-SHELL
        echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
        echo "DEVICE=eth1\nBOOTPROTO=static\nBROADCAST=192.168.1.255\nIPADDR=192.168.1.194\nNETMASK=255.255.255.192\nNETWORK=192.168.1.192\nGATEWAY=192.168.1.193\nONBOOT=yes\nDEFROUTE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth1
        systemctl restart network
      SHELL


      ##VLANS
      when "testClient1"    
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          modprobe 8021q
          echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
          echo "DEVICE=eth1.10\nVLAN=yes\nBOOTPROTO=static\nBROADCAST=10.10.10.255\nIPADDR=10.10.10.254\nNETMASK=255.255.255.0\nNETWORK=10.10.10.0\nGATEWAY=10.10.10.10\nONBOOT=yes\nDEFROUTE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth1.10
          systemctl restart network
        SHELL
      when "testClient2"    
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          modprobe 8021q
          echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
          echo "DEVICE=eth1.20\nVLAN=yes\nBOOTPROTO=static\nBROADCAST=10.10.10.255\nIPADDR=10.10.10.254\nNETMASK=255.255.255.0\nNETWORK=10.10.10.0\nGATEWAY=10.10.10.10\nONBOOT=yes\nDEFROUTE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth1.20
          systemctl restart network
        SHELL
      when "testServer1"    
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          modprobe 8021q
          echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
          echo "DEVICE=eth1.10\nVLAN=yes\nBOOTPROTO=static\nBROADCAST=10.10.10.255\nIPADDR=10.10.10.1\nNETMASK=255.255.255.0\nNETWORK=10.10.10.0\nGATEWAY=10.10.10.10\nONBOOT=yes\nDEFROUTE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth1.10
          systemctl restart network
        SHELL
      when "testServer2"    
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          modprobe 8021q
          echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
          echo "DEVICE=eth1.20\nVLAN=yes\nBOOTPROTO=static\nBROADCAST=10.10.10.255\nIPADDR=10.10.10.1\nNETMASK=255.255.255.0\nNETWORK=10.10.10.0\nGATEWAY=10.10.10.10\nONBOOT=yes\nDEFROUTE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth1.20
          systemctl restart network
      SHELL
    end
  end
end
end

