# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp-vagrant/centos-7.4"
	config.vm.box_check_update = false
	if Vagrant.has_plugin?("vagrant-proxyconf")
		config.proxy.http     = ENV['http_proxy']
		config.proxy.https    = ENV['https_proxy']
		config.proxy.no_proxy = ENV['no_proxy']
	end
	config.vm.define "nginx" do |server|
		server.vm.hostname = "nginx"
		server.vm.network "forwarded_port", guest: 8080, host: 8080
			server.vm.provider "virtualbox" do |vb|
			vb.gui = false
			vb.memory = "256"
			vb.name = "nginx"
		end
	end
end
