version: '2'
services:
  php:
    image: php:fpm
    container_name: php
    volumes:
    - ./index.php:/usr/share/nginx/html/index.php:rw
    networks:
    - net1
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - "8000:80"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
    - php:rw
    networks:
    - net1
    depends_on:
    - php
networks:
  net1: