# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp-vagrant/centos-7.4"
	config.vm.box_check_update = false
	if Vagrant.has_plugin?("vagrant-proxyconf")
		config.proxy.http     = ENV['http_proxy']
		config.proxy.https    = ENV['https_proxy']
		config.proxy.no_proxy = ENV['no_proxy']
	end
	config.vm.define "ipaserv" do |server|
		server.vm.network "forwarded_port", guest: 443, host: 443
		server.vm.hostname = "ipaserv.otus.test"
		server.vm.network :private_network, ip: "192.168.50.4", virtualbox__intnet: "otus"
			server.vm.provider "virtualbox" do |vb|
			vb.gui = false
			vb.memory = "1024"
			vb.name = "ipaserv"
		end
	end
	config.vm.define "ipacl" do |client|
		client.vm.hostname = "ipacl.otus.test"
		client.vm.network :private_network, ip: "192.168.50.5", virtualbox__intnet: "otus"
			client.vm.provider "virtualbox" do |vb|
			vb.gui = false
			vb.memory = "256"
			vb.name = "ipacl"
		end
	end
	config.vm.provision "shell", inline: <<-SHELL
	mkdir -p ~root/.ssh
	cp ~vagrant/.ssh/auth* ~root/.ssh
	yum update
	firewall-cmd --permanent --add-port={80/tcp,443/tcp,389/tcp,636/tcp,88/tcp,464/tcp,53/tcp,88/udp,464/udp,53/udp,123/udp}
	firewall-cmd --reload
	yum install bind-utils epel-release
	yum -y install ipa-server ipa-server-dns bind bind-dyndb-ldap haveged
	systemctl enable haveged
	systemctl start haveged
	ipa-server-install -U --hostname=$(hostname) -r OTUS.TEST -n otus.test -p 12345678 -a 12345678 --setup-dns --no-forwarders --no-reverse
SHELL
end
